name: Execute_simple_exporter
on: push

jobs:
  export-job:
    runs-on: ubuntu-latest
    env:
        LIA_FILE_NAME: "LiaScript.md"
        ROOT_FOLDER_NAME: "Simple_LiaDocument"
        OUTPUT_FOLDER_NAME: "export"
    steps:    
    - name: Install dependencies
      run: |
           npm install -g @liascript/exporter --unsafe-perm

    - name: Check out current repository
      uses: actions/checkout@v2
      with: 
       ref: dev

    - name: Set folders
      run: |
           echo "OUTPUT_PATH=$(echo $ROOT_FOLDER_NAME/$OUTPUT_FOLDER_NAME)" >> $GITHUB_ENV
           echo "INPUT_LIA=$(echo $ROOT_FOLDER_NAME/$LIA_FILE_NAME)" >> $GITHUB_ENV

    - name: Generate export
      run: | 
           liaex -i ${{ env.INPUT_LIA }} -f scorm2004 -o ${{ env.OUTPUT_PATH }}/scorm2004
           git add ${{ env.OUTPUT_PATH }}/scorm2004.zip

    - name: Update history file
      run: | 
           echo "---------------------------------------" > ${{ env.OUTPUT_PATH }}/history.md
           echo "$(date +%d-%m-%Y_%H-%M-%S)" | tee -a ${{ env.OUTPUT_PATH }}/history.md
           echo "${{ github.event.head_commit.message }}" | tee -a ${{ env.OUTPUT_PATH }}/history.md
           echo "${{ github.event.pusher.name }}" | tee -a ${{ env.OUTPUT_PATH }}/history.md
           cat ${{ env.OUTPUT_PATH }}/history.md
           git add ${{ env.OUTPUT_PATH }}/history.md

    - name: Commit changes
      run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git status
           git commit -m "Add new version of exported LiaScript files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: dev