name: Execute_liascript_exporters
on: push

jobs:
  export-job:
    runs-on: ubuntu-latest

    env:
        LIA_FILE_NAME: "LiaScript.md"
        ROOT_FOLDER_NAME: "LiaScriptCourse"
        OUTPUT_FOLDER_NAME: "export"

    steps:    
    - name: Install dependencies
      run: |
           npm install -g @liascript/exporter --unsafe-perm

    - name: Check out current repository
      uses: actions/checkout@v2
      with: 
       ref: dev

    - name: Set folders
      run: |
           echo "OUTPUT_PATH=$(echo $OUTPUT_FOLDER_NAME)" >> $GITHUB_ENV
           echo "INPUT_LIA=$(echo $ROOT_FOLDER_NAME/$LIA_FILE_NAME)" >> $GITHUB_ENV

    - name: Generate export
      run: | 
           # scorm2004
           liaex -i ${{ env.INPUT_LIA }} -f scorm2004 -o ${{ env.OUTPUT_PATH }}/scorm2004
           git add ${{ env.OUTPUT_PATH }}/scorm2004.zip

           # scorm2004-iframe
           liaex -i ${{ env.INPUT_LIA }} -f scorm2004 -o ${{ env.OUTPUT_PATH }}/scorm2004-iframe --scorm-iframe
           git add ${{ env.OUTPUT_PATH }}/scorm2004-iframe.zip

           # scorm1.2
           liaex -i ${{ env.INPUT_LIA }} -f scorm1.2 -o ${{ env.OUTPUT_PATH }}/scorm12
           git add ${{ env.OUTPUT_PATH }}/scorm12.zip

           # scorm1.2-iframe
           liaex -i ${{ env.INPUT_LIA }} -f scorm1.2 -o ${{ env.OUTPUT_PATH }}/scorm12-iframe --scorm-iframe
           git add ${{ env.OUTPUT_PATH }}/scorm12-iframe.zip

           # pdf
           liaex -i ${{ env.INPUT_LIA }} -f pdf -o ${{ env.OUTPUT_PATH }}/portableDocumentFormat
           git add ${{ env.OUTPUT_PATH }}/portableDocumentFormat.pdf

    - name: Commit all export results
      run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git status
           git commit -m "Add new version of exported LiaScript files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: dev